version = 0.1
[default.deploy.parameters]
stack_name = "safari-planner-backend"
resolve_s3 = true
s3_prefix = "safari-planner-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
