AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  safari-planner-backend
  Sample SAM Template for safari-planner-backend

Parameters:
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: The ID of the Bedrock model to use for generating itineraries

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.9
    Environment:
      Variables:
        DYNAMODB_TABLE: safari-planner-requests
        VERIFICATION_TABLE: !Ref VerificationTable
        REGION: !Ref AWS::Region

Resources:
  SafariPlannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          PROCESS_FUNCTION_NAME: !Ref ProcessItineraryFunction
      Policies:
        - DynamoDBCrudPolicy:
            TableName: safari-planner-requests
        - DynamoDBCrudPolicy:
            TableName: safari-planner-verification
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
                - ses:VerifyEmailIdentity
                - lambda:InvokeFunction
              Resource: 
                - '*'
                - !GetAtt ProcessItineraryFunction.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /safari-planner
            Method: post
            RestApiId: !Ref SafariPlannerApi

  ProcessItineraryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: process_itinerary.lambda_handler
      Runtime: python3.9
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          REQUESTS_TABLE: !Ref RequestsTable
          BEDROCK_MODEL_ID: !Ref BedrockModelId
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RequestsTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: 
                - "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0"
                - "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0"
                - "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0"
                - "arn:aws:bedrock:us-east-1:488210324868:inference-profile/us.anthropic.claude-3-5-haiku-20241022-v1:0"
      Events:
        ProcessItinerary:
          Type: Api
          Properties:
            Path: /process-itinerary
            Method: post
            RestApiId: !Ref SafariPlannerApi

  CheckStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: check_status.lambda_handler
      Environment:
        Variables:
          DYNAMODB_TABLE: safari-planner-requests
          VERIFICATION_TABLE: !Ref VerificationTable
          REGION: !Ref AWS::Region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: safari-planner-requests
        - DynamoDBCrudPolicy:
            TableName: !Ref VerificationTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /check-status
            Method: get
            RestApiId: !Ref SafariPlannerApi

  UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: update_status.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: safari-planner-requests
        - DynamoDBCrudPolicy:
            TableName: !Ref VerificationTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
                - ses:VerifyEmailIdentity
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /update-status
            Method: post
            RestApiId: !Ref SafariPlannerApi

  SearchRequestsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: search_requests.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: safari-planner-requests
        - DynamoDBCrudPolicy:
            TableName: !Ref VerificationTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
                - ses:VerifyEmailIdentity
              Resource: '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /search
            Method: get
            RestApiId: !Ref SafariPlannerApi

  RequestVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: request_verification.lambda_handler
      Environment:
        Variables:
          VERIFICATION_TABLE: !Ref VerificationTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VerificationTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/safari-planner/mailersend/api-key'
      Events:
        RequestVerification:
          Type: Api
          Properties:
            Path: /request-verification
            Method: post
            RestApiId: !Ref SafariPlannerApi
            Auth:
              Authorizer: NONE
      Layers:
        - !Ref RequestVerificationLayer

  SafariPlannerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: NONE
        Authorizers: {}
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With,Accept'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: "'true'"

  RequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: safari-planner-requests
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  VerificationTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: safari-planner-verification
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  RequestVerificationLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: request-verification-dependencies
      Description: Dependencies for RequestVerificationFunction
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Retain

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${SafariPlannerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  SafariPlannerFunction:
    Description: "Safari Planner Lambda Function ARN"
    Value: !GetAtt SafariPlannerFunction.Arn
  SafariPlannerApi:
    Description: "API Gateway ARN"
    Value: !Ref SafariPlannerApi
  SafariPlannerApiEndpoint:
    Description: "API Gateway Endpoint"
    Value: !Sub "https://${SafariPlannerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/safari-planner" 